spring.application.name=cookandshare

server.port= 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cook&share
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

api-endpoint = /api/v1

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true